# Generated by Django 4.2 on 2023-04-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesteps',
            name='step_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipesteps',
            name='instruction',
            field=models.TextField(),
        ),
    ]
