# Generated by Django 4.2 on 2023-04-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipesteps_step_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeSteps',
            new_name='RecipeStep',
        ),
    ]
